GET http://localhost:3001/producto

###
GET http://localhost:3001/producto/complete

###
GET http://localhost:3001/producto/complete/1


###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image1.jpg",
    "nombre": "Ibuprofeno",
    "marca": "Advil",
    "presentacion": "Caja con 20 tabletas",
    "descripcion": "Uso para el tratamiento del dolor y fiebre.",
    "precio": 15.99,
    "stock": 200,
    "contraindicaciones": "No usar en caso de úlceras gástricas.",
    "advertencias": "Consultar al médico si la fiebre persiste por más de 3 días.",
    "receta": false,
    "idBotica": 1
}


###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image2.jpg",
    "nombre": "Amoxicilina",
    "marca": "Amoxil",
    "presentacion": "Frasco con 250 mg x 14 cápsulas",
    "descripcion": "Tratamiento de infecciones bacterianas.",
    "precio": 22.50,
    "stock": 150,
    "contraindicaciones": "No usar si es alérgico a la penicilina.",
    "advertencias": "Puede causar diarrea; si persiste, consulte a su médico.",
    "receta": true,
    "idBotica": 1
}

###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image3.jpg",
    "nombre": "Paracetamol",
    "marca": "Tylenol",
    "presentacion": "Caja con 30 tabletas",
    "descripcion": "Alivio de fiebre y dolor leve a moderado.",
    "precio": 10.50,
    "stock": 300,
    "contraindicaciones": "Evitar en caso de enfermedad hepática severa.",
    "advertencias": "No exceder la dosis recomendada.",
    "receta": false,
    "idBotica": 1
}

###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image4.jpg",
    "nombre": "Omeprazol",
    "marca": "Prilosec",
    "presentacion": "Caja con 20 cápsulas",
    "descripcion": "Uso para tratar problemas gástricos como el reflujo.",
    "precio": 18.75,
    "stock": 80,
    "contraindicaciones": "No recomendado en caso de alergias a benzimidazoles.",
    "advertencias": "Consultar al médico si los síntomas persisten.",
    "receta": true,
    "idBotica": 1
}

###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image5.jpg",
    "nombre": "Loratadina",
    "marca": "Claritin",
    "presentacion": "Caja con 10 tabletas",
    "descripcion": "Alivio de los síntomas de alergias estacionales.",
    "precio": 14.00,
    "stock": 120,
    "contraindicaciones": "No usar en caso de alergia a loratadina.",
    "advertencias": "Puede causar somnolencia en algunas personas.",
    "receta": false,
    "idBotica": 1
}

###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image6.jpg",
    "nombre": "Cetirizina",
    "marca": "Zyrtec",
    "presentacion": "Caja con 10 tabletas",
    "descripcion": "Alivio de los síntomas de rinitis alérgica.",
    "precio": 12.99,
    "stock": 90,
    "contraindicaciones": "Evitar en caso de alergias a cetirizina.",
    "advertencias": "Puede causar somnolencia.",
    "receta": false,
    "idBotica": 1
}

###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image7.jpg",
    "nombre": "Metformina",
    "marca": "Glucophage",
    "presentacion": "Caja con 30 tabletas",
    "descripcion": "Uso para el tratamiento de la diabetes tipo 2.",
    "precio": 25.00,
    "stock": 70,
    "contraindicaciones": "No usar en caso de insuficiencia renal severa.",
    "advertencias": "Consultar al médico regularmente.",
    "receta": true,
    "idBotica": 1
}

###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image8.jpg",
    "nombre": "Simvastatina",
    "marca": "Zocor",
    "presentacion": "Caja con 30 tabletas",
    "descripcion": "Uso para reducir el colesterol y triglicéridos.",
    "precio": 23.50,
    "stock": 65,
    "contraindicaciones": "No usar en caso de enfermedad hepática activa.",
    "advertencias": "Consultar al médico antes de iniciar el tratamiento.",
    "receta": true,
    "idBotica": 1
}

###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image9.jpg",
    "nombre": "Aspirina",
    "marca": "Bayer",
    "presentacion": "Caja con 40 tabletas",
    "descripcion": "Uso para el alivio del dolor y prevención de infartos.",
    "precio": 8.99,
    "stock": 250,
    "contraindicaciones": "No usar en caso de úlceras estomacales.",
    "advertencias": "Puede causar sangrado gastrointestinal.",
    "receta": false,
    "idBotica": 1
}

###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image10.jpg",
    "nombre": "Lisinopril",
    "marca": "Prinivil",
    "presentacion": "Caja con 20 tabletas",
    "descripcion": "Uso para el tratamiento de la hipertensión arterial.",
    "precio": 20.00,
    "stock": 110,
    "contraindicaciones": "No usar en caso de angioedema previo.",
    "advertencias": "Consultar al médico regularmente.",
    "receta": true,
    "idBotica": 1
}

###
POST http://localhost:3001/producto
Content-Type: application/json

{
    "imagen": "https://example.com/image15.jpg",
    "nombre": "Diclofenaco",
    "marca": "Voltaren",
    "presentacion": "Caja con 20 tabletas de 50 mg",
    "descripcion": "Uso para el alivio del dolor e inflamación.",
    "precio": 18.00,
    "stock": 140,
    "contraindicaciones": "No usar en caso de úlceras gástricas activas.",
    "advertencias": "Consultar al médico si el dolor persiste.",
    "receta": false,
    "idBotica": 2
}



###

###

###

###