POST http://localhost:3001/suscripcion/create
Content-Type: application/json

{
    "userId": 2,
    "subsType": "3 meses",
    "totalCartPrice": 100,
    "cartProducts": [
        { "productId": 1, "cantidad": 2, "recetaId": null },
        { "productId": 2, "cantidad": 1, "recetaId": null }
    ]
}

###

GET http://localhost:3001/suscripcion

###

DELETE http://localhost:3001/suscripcion

###

POST http://localhost:3001/suscripcion/cancel/1

###

GET http://localhost:3001/kit

###

GET http://localhost:3001/kit_producto

###
GET http://localhost:3001/kit_producto/complete/23
